import { AnalysisResult, ScamJourneyStage, TrustChainNode, TrustChainRelationship } from "@/types";

/**
 * Example Trust Chain demonstration data.
 * Adheres strictly to safety policy: uses fictional domains (e.g., example-finance.test)
 * and clear demonstration indicators.
 */
export const MOCK_TRUST_CHAIN_NODES: TrustChainNode[] = [
  {
    id: "node-claim",
    label: "High-Yield Guarantee Claim",
    type: "claim",
    status: "CONTRADICTORY",
    claimedValue: "Guaranteed 35% monthly ROI under SEBI RIA License #INA000099999",
    verifiedValue: "SEBI regulations prohibit guaranteed returns for registered advisors",
    description: "Claim of guaranteed return contradicts statutory SEBI Investment Adviser regulations (2013).",
    details: "Statutory circular SEBI/HO/MIRSD/DOS3/CIR/P/2018/140 strictly forbids any registered entity from offering assured returns.",
  },
  {
    id: "node-entity",
    label: "Claimed Corporate Entity",
    type: "entity",
    status: "UNVERIFIED",
    claimedValue: "Example Wealth Advisors Private Limited",
    verifiedValue: "No exact match found in MCA corporate database under claimed state jurisdiction",
    description: "Corporate name provided does not match registered CIN records.",
    details: "The MCA public directory shows similar names, but registered addresses and directors do not correlate with claimed promoters.",
  },
  {
    id: "node-registration",
    label: "Regulatory License Record",
    type: "registration",
    status: "CONTRADICTORY",
    claimedValue: "SEBI RIA #INA000099999",
    verifiedValue: "License #INA000099999 belongs to an unrelated retired entity registered in 2017",
    description: "License number is borrowed or cloned from an unrelated party.",
    details: "SEBI public intermediary registry lists this registration number for a different individual with no affiliation to example-finance.test.",
  },
  {
    id: "node-identity",
    label: "Official Key Persons Identity",
    type: "official_identity",
    status: "UNKNOWN",
    claimedValue: "Claimed Chief Strategist: 'Dr. R. Sharma'",
    verifiedValue: "Stock image detected; no verified professional profile matching claimed credentials",
    description: "Identity cannot be independently confirmed through public directories.",
    details: "Reverse image inspection points to standard commercial stock photography used across unrelated portals.",
  },
  {
    id: "node-website",
    label: "Web Infrastructure",
    type: "website",
    status: "UNVERIFIED",
    claimedValue: "https://example-finance.test",
    verifiedValue: "Domain age: 14 days; Privacy-masked WHOIS; Generic shared hosting",
    description: "Newly registered domain lacking corporate contact verifiable records.",
    details: "Domain registered via overseas registrar with anonymized ownership, despite claiming 10+ years operating history in India.",
  },
  {
    id: "node-app",
    label: "Mobile Application Vector",
    type: "app",
    status: "UNKNOWN",
    claimedValue: "Direct APK download link shared via messaging channel",
    verifiedValue: "Not present on official Google Play Store or Apple App Store",
    description: "Third-party sideloaded application bypassing app store security reviews.",
    details: "Sideloaded APKs pose severe risks of unauthorized SMS interception and device screen capture.",
  },
  {
    id: "node-social",
    label: "Communication Channel",
    type: "social_account",
    status: "UNVERIFIED",
    claimedValue: "Telegram Group: 'VIP Institutional IPO Insights'",
    verifiedValue: "Anonymous channel with comments restricted and admin handle obscured",
    description: "Unverified private group creating artificial urgency and peer validation.",
    details: "Group exhibits bot-driven activity mimicking fake profit screenshots from other participants.",
  },
  {
    id: "node-payment",
    label: "Payment & Settlement Identity",
    type: "payment_identity",
    status: "CONTRADICTORY",
    claimedValue: "Institutional Escrow Account",
    verifiedValue: "Individual savings account handle: rahul9821@upi (Personal payee)",
    description: "Funds directed to personal UPI handle rather than SEBI-compliant corporate client account.",
    details: "Legitimate SEBI intermediaries must collect fees/funds only in officially designated, audited bank accounts.",
  },
];

export const MOCK_TRUST_CHAIN_RELATIONSHIPS: TrustChainRelationship[] = [
  {
    fromNodeId: "node-claim",
    toNodeId: "node-entity",
    relationType: "asserted_by",
    status: "UNVERIFIED",
    notes: "Claim made in the name of an unconfirmed entity",
  },
  {
    fromNodeId: "node-entity",
    toNodeId: "node-registration",
    relationType: "cites_license",
    status: "CONTRADICTORY",
    notes: "Registration number belongs to an unrelated third party",
  },
  {
    fromNodeId: "node-registration",
    toNodeId: "node-identity",
    relationType: "issued_to",
    status: "UNKNOWN",
    notes: "Promoter persona cannot be tied to actual license holder",
  },
  {
    fromNodeId: "node-identity",
    toNodeId: "node-website",
    relationType: "operates_portal",
    status: "UNVERIFIED",
    notes: "Portal registered 14 days ago without corporate identity linkage",
  },
  {
    fromNodeId: "node-website",
    toNodeId: "node-app",
    relationType: "distributes_app",
    status: "UNKNOWN",
    notes: "Direct APK distributed outside verified app marketplaces",
  },
  {
    fromNodeId: "node-website",
    toNodeId: "node-social",
    relationType: "funnels_to",
    status: "UNVERIFIED",
    notes: "Redirects visitors to private unmonitored group chat",
  },
  {
    fromNodeId: "node-social",
    toNodeId: "node-payment",
    relationType: "directs_funds_to",
    status: "CONTRADICTORY",
    notes: "Group admins provide personal UPI handles instead of registered banking channels",
  },
];

export const MOCK_SCAM_JOURNEY_STAGES: ScamJourneyStage[] = [
  {
    id: "stage-1",
    order: 1,
    stageName: "Initial contact",
    description: "Unsolicited WhatsApp, Telegram or social media invitation to an 'exclusive institutional trading group'.",
    observedSignals: ["Unsolicited message", "High-return pitch", "False exclusivity"],
    status: "OBSERVED",
    riskSeverity: "HIGH",
  },
  {
    id: "stage-2",
    order: 2,
    stageName: "Financial claim",
    description: "Presentation of guaranteed 30-50% monthly profit or privileged 'pre-IPO quota' with fake SEBI certificates.",
    observedSignals: ["Guaranteed return language", "Cloned regulatory license", "Urgency countdown"],
    status: "OBSERVED",
    riskSeverity: "HIGH",
  },
  {
    id: "stage-3",
    order: 3,
    stageName: "Website",
    description: "Visitor directed to a modern-looking financial portal (e.g. example-finance.test) registered just days prior.",
    observedSignals: ["Recent domain registration (<30 days)", "Stock imagery", "Anonymized WHOIS"],
    status: "OBSERVED",
    riskSeverity: "HIGH",
  },
  {
    id: "stage-4",
    order: 4,
    stageName: "Communication channel",
    description: "Private mentor messaging channel with peer bots posting fake profit receipts and encouraging participation.",
    observedSignals: ["Unidirectional broadcast", "Fabricated testimonials", "Pressure tactics"],
    status: "SUSPECTED",
    riskSeverity: "MEDIUM",
  },
  {
    id: "stage-5",
    order: 5,
    stageName: "Deposit request",
    description: "Victim requested to transfer initial capital to an individual UPI handle or personal savings account.",
    observedSignals: ["Personal UPI handle", "Third-party mule account", "Lack of formal invoice"],
    status: "SUSPECTED",
    riskSeverity: "HIGH",
  },
  {
    id: "stage-6",
    order: 6,
    stageName: "Withdrawal issue",
    description: "When withdrawal is requested, victim is told funds are locked pending '20% regulatory tax clearance fee'.",
    observedSignals: ["Advance-fee fraud pattern", "Fabricated tax demand", "Account freeze threats"],
    status: "POTENTIAL_NEXT",
    riskSeverity: "HIGH",
  },
];

export const MOCK_ANALYSIS_RESULT: AnalysisResult = {
  id: "assessment-mock-001",
  targetArtifact: "https://example-finance.test",
  inputMode: "website",
  analyzedAt: "Demonstration Assessment Preview",
  overallConcern: "HIGH",
  primaryReasons: [
    "Regulatory claim requires verification",
    "Identity relationship is unverified",
    "Financial pressure language detected",
  ],
  findings: {
    whatWeFound: [
      "Target portal domain 'example-finance.test' was registered 14 days ago via privacy-proxy service.",
      "The portal displays claims of 'Official SEBI Registration No. INA000099999' on its homepage footer.",
      "The landing page contains high-urgency promises: 'Guaranteed 35% monthly returns, 100% principal protection'.",
      "Direct payment instructions in chat channels reference an individual UPI handle ('rahul9821@upi') rather than an institutional current account.",
    ],
    whatWeVerified: [
      "SEBI Intermediary Registry database check: Registration number INA000099999 was issued in 2017 to an unrelated individual with no corporate relationship to example-finance.test.",
      "Ministry of Corporate Affairs (MCA) database check: No company incorporation record exists under the claimed exact legal trade name.",
      "DNS & Infrastructure: The web server is located on offshore shared hosting with no enterprise compliance certificates.",
    ],
    whatRemainsUncertain: [
      "The true physical identity and geographical location of the domain operators cannot be determined due to privacy proxy masking.",
      "Whether the promoted mobile APK contains embedded keystroke logging or malicious permission escalation payloads has not been sandboxed in this view.",
      "The extent of other connected promotional domains operating under the same network cluster.",
    ],
    whyFlagged: [
      "Statutory Contradiction: Under SEBI (Investment Advisers) Regulations, 2013, no regulated entity is permitted to promise assured or guaranteed returns.",
      "Regulatory Impersonation: Using another entity's registered license number without authorization is a critical trust chain failure.",
      "Mule Payment Pattern: Requesting investment capital deposits into personal UPI IDs bypasses standard banking escrow protocols.",
      "Temporal Disconnect: The platform asserts a 10-year market track record, while the underlying web domain was created less than two weeks ago.",
    ],
  },
  riskSignals: [
    {
      id: "sig-1",
      severity: "HIGH",
      title: "Regulatory License Impersonation",
      description: "Claimed SEBI RIA license corresponds to a completely different holder in official records.",
      category: "registry",
    },
    {
      id: "sig-2",
      severity: "HIGH",
      title: "Statutory Violation: Guaranteed ROI",
      description: "Promises of assured 35% returns violate SEBI investor protection regulations.",
      category: "content",
    },
    {
      id: "sig-3",
      severity: "HIGH",
      title: "Individual UPI Deposit Routing",
      description: "Payment identity resolves to an individual VPA, not a regulated corporate client account.",
      category: "financial",
    },
    {
      id: "sig-4",
      severity: "MEDIUM",
      title: "Fresh Domain Infrastructure",
      description: "Website registered only 14 days ago contradicts claim of multi-year operational pedigree.",
      category: "domain",
    },
  ],
  trustChainNodes: MOCK_TRUST_CHAIN_NODES,
  trustChainRelationships: MOCK_TRUST_CHAIN_RELATIONSHIPS,
  scamJourneyStages: MOCK_SCAM_JOURNEY_STAGES,
  safeNextSteps: [
    "Do NOT deposit funds or authorize UPI mandates to any personal address or unverified payment handle.",
    "Independently verify broker/adviser credentials directly at SEBI's official portal: sebi.gov.in (Recognized Intermediaries section).",
    "Cross-check company registration number (CIN) directly on the Ministry of Corporate Affairs portal: mca.gov.in.",
    "Do NOT install third-party APKs sent via Telegram or WhatsApp; stick strictly to official verified app stores.",
    "If you have already transferred funds, immediately call the National Cyber Crime Helpline at 1930 and file a complaint on cybercrime.gov.in.",
  ],
  isMockExample: true,
};
